version: "3.9"   
services:
  web:
   build: .
   container_name: ktm_django
   ports: 
    - 8000:8000
   command: >
    sh -c  "python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000" 

   depends_on:
    db:
      condition: service_started

   environment:
    - DB_NAME=ktm
    - DB_USER=sito
    - DB_PASSWORD=sito
    - DB_HOST=db 
  db:
    image: mysql:8
    container_name: ktm_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ktm
      - MYSQL_USER=sito
      - MYSQL_PASSWORD=sito
