# Generated by Django 3.2.9 on 2021-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
