# Generated by Django 3.2.7 on 2021-12-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0002_auto_20211202_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a project name (e.g. Task Managment Project)', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the project', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Enter a task name (e.g. Design)', max_length=200)),
                ('task_description', models.TextField(help_text='Enter a brief description of the task', max_length=1000)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaskManagement.project')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Taskmanagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('TD', 'To do'), ('IP', 'In Progress'), ('C', 'Completed')], default='C', help_text='Tasks Status', max_length=2)),
                ('priority', models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Meduim'), ('L', 'Low')], default='l', help_text='Tasks Priorities', max_length=1)),
                ('comment', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Taskmanagment', to='TaskManagement.employee')),
                ('assigneedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammamember', to='TaskManagement.employee')),
                ('task_managment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaskManagement.task')),
            ],
            options={
                'ordering': ['end_date'],
                'permissions': (('can_mark_completed', 'Set task as completed'),),
            },
        ),
    ]
